# Generated by Django 4.0.4 on 2022-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('STATUS_TODO', 'Not Started'), ('STATUS_IN_PROGRESS', 'In Progress'), ('STATUS_COMPLETED', 'Completed'), ('STATUS_DONE', 'Done')], max_length=120),
        ),
    ]
